version: "3"

tasks:
  build:
    cmd: dotnet build  --no-incremental

  format:
    cmd: dotnet format $DIR --severity error
    env:
      DIR: .

  test:
    cmd: dotnet test -v m

  test-coverage:
    cmd: dotnet test /p:CollectCoverage=true

  coverage-report:
    cmds:
      - rm -rf ./TestResults && dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults -v q
      - reportgenerator -reports:./TestResults/**/coverage.cobertura.xml -targetdir:coveragereport/ -reporttypes:Html_Dark

  full-clean:
    cmd: rm -rf ./**/**/obj ./**/**/bin && dotnet clean

  docker-build:
    dir: $DIR
    cmd: docker build --build-arg PROJECT={{.PROJECT}} -t {{.IMAGE_NAME}} $DIR
    env:
      DIR: .

  scan:
    dir: .
    cmd: semgrep scan --config "p/csharp" --config "p/secrets"
